name: Windows

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      #- name: Install cmake
      #  run: choco install cmake

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Config
        run: cmake -G Ninja -B cmake-build

      - name: Build
        run: cmake --build cmake-build
